doctrine_migrations:
    dir_name:            '%kernel.project_dir%/src/Migrations'
    namespace:           'App\Migrations'
    table_name:          "core23_version"
    organize_migrations: "BY_YEAR"
