doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'

        types:
            json: Sonata\Doctrine\Types\JsonType

            App\Domain\Model\Medicine\FlagId:     App\Infrastructure\Persistence\Entity\Medicine\FlagId
            App\Domain\Model\Medicine\ProductId:  App\Infrastructure\Persistence\Entity\Medicine\ProductId
            App\Domain\Model\Medicine\ProducerId: App\Infrastructure\Persistence\Entity\Medicine\ProducerId

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Entity'
                prefix: 'App\Infrastructure\Persistence\Entity'
                alias: App

