framework:
    translator:
        paths:
            - '%kernel.root_dir%/../translations/'
        fallbacks:   [ 'en' ]
    secret:          '%env(APP_SECRET)%'
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    session:
         handler_id:  session.handler.native_file
         save_path:   '%kernel.project_dir%/var/sessions/%kernel.environment%'
         cookie_secure: auto
         cookie_samesite: lax

    fragments:       ~
    http_method_override: true
    php_errors:
        log: true
