sonata_seo:
    encoding:           'UTF-8'
    page:
        title:          "%sonata_seo.title%"
        separator:      ' - '
        metas:
            name:
                viewport:             'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no'

            http-equiv:
                'Content-Type':       'text/html; charset=utf-8'
                'X-Ua-Compatible':    'IE=edge'

            property:
                'og:image':       "%sonata_seo.image%"

        head:
            'xmlns':              'http://www.w3.org/1999/xhtml'
            'xmlns:og':           'http://opengraphprotocol.org/schema/'
            'xml:lang':           'de'
            'og:type':            'website'
