cmf_routing:
    chain:
        routers_by_id:
            sonata.page.router: 150
            router.default: 100

sonata_block:
    context_manager: sonata.page.block.context_manager
    default_contexts: [sonata_page_bundle, sonata_dashboard_bundle]

    container:
        types:
            - sonata.block.service.container
            - sonata.page.block.container
            - sonata.dashboard.block.container
            - cmf.block.container
            - cmf.block.slideshow
        templates:

sonata_admin:
    assets:
        extra_javascripts:
            - bundles/sonatapage/sonata-page.back.min.js
        extra_stylesheets:
            - bundles/sonatapage/sonata-page.back.min.css

sonata_page:
    hide_disabled_blocks:  true

    cache_invalidation:
        service:  sonata.page.cache.invalidation.simple
        recorder: sonata.page.cache.recorder
        classes:
            "App\\Entity\\Page\\Block": getId

    page_defaults:
        homepage: { decorate: false, enabled: true }

    slugify_service: sonata.core.slugify.cocur
    multisite: host
    use_streamed_response: false

    router_auto_register:
        enabled: true
        priority: 150
    ignore_route_patterns:
        - ^(.*)admin(.*)
        - ^_(.*)
    ignore_routes:
        - sonata_page_cache_esi
        - sonata_page_cache_ssi
        - sonata_page_js_sync_cache
        - sonata_page_js_async_cache
        - sonata_cache_esi
        - sonata_cache_ssi
        - sonata_cache_js_async
        - sonata_cache_js_sync
        - sonata_cache_apc
    ignore_uri_patterns:
        - ^/admin\/

    default_template: default
    templates:
        default:
            path: '@SonataPage/layout.html.twig'
            name: 'default'
            containers:
                content_top:
                    name: Top content
                content:
                    name: Main content
                content_bottom:
                    name: Bottom content
                footer:
                    name: Footer
            matrix:
                layout: |
                    TTTTTTTT
                    TTTTTTTT
                    CCCCCCCC
                    CCCCCCCC
                    BBBBBBBB
                    BBBBBBBB
                    FFFFFFFF
                    FFFFFFFF

                mapping:
                    T: content_top
                    C: content
                    B: content_bottom
                    F: footer

    direct_publication: '%kernel.debug%'

    catch_exceptions:
        not_found: [404,405]
        fatal:     [500]

    class:
        site:       'App\Infrastructure\Persistence\Entity\Page\Site'
        page:       'App\Infrastructure\Persistence\Entity\Page\Page'
        block:      'App\Infrastructure\Persistence\Entity\Page\Block'
        snapshot:   'App\Infrastructure\Persistence\Entity\Page\Snapshot'
